### ISSUE TITLE
[Proposal] Dev packages install

### ISSUE THREAD

**Issue by terion-name** [rtablada/package-installer#15]
Hi.
What about dev-packages installation? I mean that set in composer.json in require-dev section.

There is a concern on registering service providers and aliases for dev-packages. See a discussion about this: https://github.com/laravel/framework/issues/1603

In my setup bash script I do the following:

```
# update composer.json

cd ${PROJECT_PATH}
composer require --no-update rtablada/package-installer:dev-master
composer require --dev --no-update loic-sharma/profiler:1.1.* way/generators:dev-master way/laravel-test-helpers:dev-master barryvdh/laravel-ide-helper:1.*
composer require --dev --no-update fzaninotto/faker:dev-master codeception/codeception:* phpunit/phpunit=3.7.*
composer update

# update configs

cd ${PROJECT_PATH}/app/start

# create a start file for development environment
echo -e '<?php\n' > ${ENV_NAME}.php

# register providers via start file (see https://github.com/laravel/framework/issues/1603#issuecomment-21864164)
# when Laravel 4.1 will be released, the ->boot() calls should be removed
echo "App::register('Way\\Generators\\GeneratorsServiceProvider')->boot();" >> ${ENV_NAME}.php
echo "App::register('Profiler\\ProfilerServiceProvider')->boot();" >> ${ENV_NAME}.php
echo "App::register('Barryvdh\\LaravelIdeHelper\\IdeHelperServiceProvider')->boot();" >> ${ENV_NAME}.php

echo -e '\n' >> ${ENV_NAME}.php

# register aliases
echo "\$loader = \\Illuminate\\Foundation\\AliasLoader::getInstance();" >> ${ENV_NAME}.php
echo "\$loader->alias('Profiler', 'Profiler\\Facades\\Profiler');" >> ${ENV_NAME}.php
```

And this works perfectly, but in case of Package Installer there would be a concern about environment name. Maybe setting this in package config should solve the problem, but it is a theme to think

**Comment by rtablada** [comment]
I see where you are coming from, but Package Installer really is only dealing right now with the main configuration file not environment start files like you are working with.

There is some discussion on best practices for require dev dependencies and you are going on a smart path, but at least right now this is not going to be really going in to the next version of Package Installer.

Think of Package Installer as a scaffolder for getting packages quickly registered into the IOC and AliasLoader, then when you need to do something more advanced (such as creating environment specific loaders), you just swap out the code you need.

**Comment by terion-name** [comment]
Ok, thanx for reply, I've got it =)
