### ISSUE TITLE
Could auto add service provider for package don't have `provides.json'?

### ISSUE THREAD

**Issue by thearabbit** [rtablada/package-installer#17]
I think that it is good, if you can add automatic (service provider / alias) for package don't have `provides.json`.

**Comment by rtablada** [comment]
I'm not sure what advantage that would give over editing the configuration file. The idea of package installer is that you would avoid having to know and look up what aliases and providers need to be registered for a package.

**Comment by thearabbit** [comment]
Very thank for your reply.
