### ISSUE TITLE
Aliases not updated

### ISSUE THREAD

**Issue by caouecs** [rtablada/package-installer#3]
Hello,
in my project, I added provides.json and I tested package-installer.
- Installation of my project : OK
- ServiceProvider : OK
- Aliases : KO

Can you help me with my provides.json file ? Thanks

https://github.com/caouecs/Laravel4-Gumby2/blob/master/provides.json

**Comment by rtablada** [comment]
I have checked on my development system and the aliases were added properly. Since array_merge doesn't move items in the case of merge conflicts, your Form Alias is shooting up to the top.

I found that all of your listed aliases were updated including
- Form
- Alert
- Badge
- Breadcrumb
- Button
- Icon
- Image
- Label
- Tabs
- Valign

Package installer does currently warn overwrites of existing aliases (in this case the Form alias). Just wanted to check that this is what you wanted.

**Comment by caouecs** [comment]
Hello,
I tried with new install of Laravel and without Form, and I have the same problem...

**Comment by rtablada** [comment]
Can you post a gist of your resulting app.php?

**Comment by rtablada** [comment]
The result of running it on my machine is this: https://gist.github.com/rtablada/5753012

Form is overwritten on line 161 while the rest of the aliases start at line 183.

**Comment by caouecs** [comment]
https://gist.github.com/caouecs/5753075

I work on Mac, PHP 5.4.10

**Comment by caouecs** [comment]
Hello,
I updated my provides.json with \ to be a valid json file, and it works… but I have \ in app.php...

**Comment by rtablada** [comment]
Send me a link to a gist with your new app.php
—

**Comment by caouecs** [comment]
Sorry, in my previous post, it was "double \ "

**Comment by rtablada** [comment]
Hmmm... I'll double check.

I know it is not valid Json, but I like having single \ and then do a replace for \. This may cause international issues though on some machines?

I'll do some more research on why this may be occurring...

**Comment by rtablada** [comment]
After thinking about it, I remember putting this into the providers, though I need to check on working on aliases...

**Comment by caouecs** [comment]
This afternoon (french hour), I will do more tests, but I think it's important to have valid json file, no ?

**Comment by rtablada** [comment]
I have updated to require valid JSON, let's see if that fixes the issue.

**Comment by caouecs** [comment]
I don't see your update on GitHub

**Comment by caouecs** [comment]
with double \ :
- ServiceProvider : OK
- Aliases : KO

I look code

**Comment by rtablada** [comment]
I had a missing merge conflict. It should be live now. The change was in the Provider's buildFromJson method. It used to do a str_replace of \ to \.

But, I have commented it out now.

**Comment by caouecs** [comment]
It works for you ? Always ko for me, I look the code if I can find the issue...

**Comment by caouecs** [comment]
In my env, I think the problem is in preg_replace() of PackageInstaller::replaceConfig()

because in PackageInstaller::updateAliases(), the value of $configAliases after array_merge() is OK, I have my aliases, but after I lose my aliases

**Comment by rtablada** [comment]
I need to check I think I'm looking for an unnecessary trailing comma. Which if aliases is your last config, it would make sense that that makes the preg_replace not match...

​I'll get to fixing that in just a min. 

—

**Comment by rtablada** [comment]
I have updated the preg replace to no longer look for the trailing comma. This should fix the prior issues.

**Comment by caouecs** [comment]
I tested your last commit 

{"error":{"type":"ErrorException","message":"preg_replace(): Compilation failed: unmatched parentheses at offset 8","file":"\/Users\/caouecs\/svn\/git\/test\/package\/vendor\/rtablada\/package-installer\/src\/Rtablada\/PackageInstaller\/ProviderCreator.php","line":35}}

**Comment by rtablada** [comment]
Yeah, I'm having some issues with my regex. I'm on vacation and will try it when I come in during mid-day heat. I have restored it to decode valid JSON.

A `composer update` should get it all up to speed again.

**Comment by rtablada** [comment]
It should be running now. I'm going to get this under test soon.

**Comment by caouecs** [comment]
See #4
