### ISSUE TITLE
Bug in PackageInstallerServiceProvider.php

### ISSUE THREAD

**Issue by sascha-wojewsky-IPD** [rtablada/package-installer#9]
Hi,

you have a bug in rtablada/package-installer/src/Rtablada/PackageInstaller/PackageInstallerServiceProvider.php in function registerInstall(). You have to use $app instead of $this->app in Line 31 and 32.

It should look like this

``` php
 protected function registerInstall()
    {
        $this->app['package.install'] = $this->app->share(function($app)
        {
            $providerCreator = new ProviderCreator($app['files'], new Provider);
            $packageInstaller = new PackageInstaller($app['files'], $app['config']);
            return new PackageInstallCommand($providerCreator, $packageInstaller);
        });
    }
```

**Comment by caouecs** [comment]
Hello,
you can propose a pull request ? Thanks

**Comment by rtablada** [comment]
I've had this on my todo list. If there's no pull request before I get back to my desk, I will fix it quickly.
